version: '2'

services:
  # Service 1 This service is going to build the image from the dockerfile
  # But you can deploy this image to dockerhub and use it that way 'image: mongo-node'
  mongo-node:
    container_name: mongo-node
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:3000"
    networks: 
      - nodeapp-network

  # Service 2
  mongodb:
    container_name: mongo
    image: mongo
    networks: 
      - nodeapp-network

networks: 
  # Network 1
  nodeapp-network:
    driver: bridge